worker_processes auto;
rtmp_auto_push on;
events {}

rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            hls on;
            hls_path /tmp/hls;
            hls_fragment 3;
            hls_playlist_length 60;
            
            # YouTube Live Production Setup:
            # Uncomment the line below and replace with your YouTube Stream URL and Key
            # push rtmp://a.rtmp.youtube.com/live2/YOUR-YOUTUBE-STREAM-KEY;
            
            deny play all; # Force viewers to use HLS instead of direct RTMP
        }
    }
}

http {
    server {
        listen 8080;
        
        # Enable CORS for HLS
        add_header Access-Control-Allow-Origin *;

        location / {
            root /www;
            index index.html;
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
        }
    }
}
